import json
from flask import Flask
from flask import render_template
app = Flask(__name__)

with open('./data.json') as f: data = json.load(f) # load json generated by generate.py

@app.route("/")
def index():
  return render_template('index.html',data=data) 

if __name__ == '__main__':
  app.run()